### ISSUE TITLE
Why not putting data directly into each enum variant?

### ISSUE THREAD

**Issue by xvitus** [Ogeon/flow#3]
Hello,
I am new to Rust, I am studying the language and all available frameworks, so I found your very valuable work.
I was just wondering why did you put the enum inside a struct instead of putting data directly into each enum variant?
What I mean is expressed [here](https://doc.rust-lang.org/book/second-edition/ch06-01-defining-an-enum.html#enum-values)

where this version with enum inside a struct:

```rust
#![allow(unused_variables)]
fn main() {
enum IpAddrKind {
    V4,
    V6,
}

struct IpAddr {
    kind: IpAddrKind,
    address: String,
}

let home = IpAddr {
    kind: IpAddrKind::V4,
    address: String::from("127.0.0.1"),
};

let loopback = IpAddr {
    kind: IpAddrKind::V6,
    address: String::from("::1"),
};
}
```

becomes this version directly in the enum, without the need to declare a scruct:

```rust
#![allow(unused_variables)]
fn main() {
enum IpAddr {
    V4(String),
    V6(String),
}

let home = IpAddr::V4(String::from("127.0.0.1"));

let loopback = IpAddr::V6(String::from("::1"));
}
```

I was wondering if there are technical reasons why you choose the struct + enum way, for learning purposes.

Thank you in advance,
--Vito.

**Comment by Ogeon** [comment]
Hi! Sorry for the late response. I have been traveling a bit and didn't find a good moment to properly respond until now. First, keep in mind that this is no longer developed, and will stay like that for the foreseeable future, and I would have done a lot of things differently if I would make a new version. That said, it's nice that it can be of help anyway!

I assume you are talking about the example in the readme:

```rust
enum NumberOp {
    Add,
    Sub,
}

struct NumberChange {
    amount: f64,
    op: NumberOp,
}
```

The general answer to your question is "it depends". In this particular case, it would only make a small difference and be more of a matter of taste. In a universe where I put it all into the operator enum, it would look like this:

```rust
extern crate flow;

use flow::{
    Dispatcher,
    DispatchContext,
    Store,
};

struct NumberStore {
    the_number: f64,
}

impl Store for NumberStore {
    // Event type and payload type are the same now
    type Payload = NumberChange;
    type Event = NumberChange;

    fn handle(&mut self, _: DispatchContext<NumberChange>, payload: &NumberChange) -> Option<NumberChange> {
        match *payload {
            NumberChange::Add(amount) => self.the_number += amount,
            NumberChange::Sub(amount) => self.the_number -= amount,
        }

        Some(payload)
    }
}

#[derive(Clone, Copy)]
enum NumberChange {
    Add(f64),
    Sub(f64),
    // Adding more operators here forces us to repeat the same payload
}

fn main() {
    let mut dispatcher = Dispatcher::new();

    dispatcher.register_store(NumberStore {
        the_number: 0.0,
    });

    //The event type has changed
    dispatcher.listen(|_: DispatchContext<NumberChange>, store: &NumberStore, event: &NumberChange| {
        // Notice the ignored fields
        match *event {
            NumberChange::Add(_) => println!("the number was increased to {}", store.the_number),
            NumberChange::Sub(_) => println!("the number was decreased to {}", store.the_number),
        }
    });

    // This part looks cleaner, but it's essentially the same
    dispatcher.dispatch(NumberChange::Add(3.14));
    dispatcher.dispatch(NumberChange::Sub(10.0));
}
```

As you can see, the big difference is that the `amount` parameter is repeated a lot and then sent to the listeners (while the original example only sends the operator). Adding more operator adds more repetition and it can get annoying to change later. Separating the operator and the amount parameter, as in the original example, reduces repetition and perhaps the risk of mistakes (because it's only defined once).

On a more abstract level, there are more aspects to it. Let's say all you want to know is the `amount`, no matter the operator. In that case it's a big difference:

```rust
let change:  NumberChange = /* ... */;

// Current example:
println!("amount: {}", change.amount);

// `amount` in enum variants:
let amount = match change {
    NumberChange::Add(amount) => amount,
    NumberChange::Sub(amount) => amount,
};
println!("amout: {}", amount);
```

so if you are working with the data separately, it's more efficient and pleasant to have it separated from the enum. You may very well want to do this in a more complex case:

```rust
struct BinaryExpression {
    operator: BinaryOperator, // the enum

    // these two expressions will have to be evaluated no matter what `operator` is
    left_hand_side: Expression,
    right_hand_side: Expression,
}
```

There are also the opposite case, where the data is different for each enum variant. In that case it's more or less necessary to have it in the variants. Like in this variant of the `IpAddress`:

```rust
enum IpAddress {
    V4([u8; 4]),
    V6([u16; 8]) // I may be wrong on the details, but I'm sure you get the point :)
}
```

In this case they cannot be "simplified" to a variant+data pair without making it harder for us to work with it.

There may be even more to it, that I'm forgetting right now, but another reason for putting enums in structs is privacy and here it doesn't matter what the enum represents. The variants of an enum are always public, so if you want to keep away from the user's eyes, you can wrap it in a simple tuple struct:

```rust
enum IpAddressKind {
    V4([u8; 4]),
    V6([u16; 8])
}

pub struct IpAddress(IpAddressKind);
```

I hope this helped clearing things up a bit!

**Comment by xvitus** [comment]
Hello Erik,

thank you very much for your very kind and exaustive response!

Actually, your explanation shows very little difference between the two
approaches.
I was expecting a more concise result from the "data in the enum" approach,
but of course I am totally new to Rust and thanks to your explanation, now
I have much more matter for my understanding.
Thank you again.

--Vito.

Il giorno mar 31 lug 2018 alle ore 17:52 Erik Hedvall <
notifications@github.com> ha scritto:

**Comment by Ogeon** [comment]
I can see why it's tempting to go with the "data in enum" approach, and I do often start out that way, but it's common that the other approach turns out to be easier to work with in the long run when the data is the same for all variants. Both are valid solutions and will probably generate more or less the same code, but the syntax and semantics comes in the way.

Anyway, feel free to ask more if anything is still unclear! You can still reuse this issue after I have closed it.
